### ISSUE TITLE
failed: [ns01] (item=None) => {"changed": false, "failed": true, "item": null, "msg": "Destination /etc/yum.repos.d/.repo does not exist !", "rc": 257}

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [bertvv/ansible-role-rh-base#9]
Not a bug but a user error. Posting for any other newish Ansible users who run into this.

The issue was I had disabled CentOS-fasttrack like so:

```yaml
rhbase_enable_repos:
#  - CentOS-fasttrack
```

This created an empty var that caused the above issue. The correct way to disable but leave in place for future use is like so:

```yaml
#rhbase_enable_repos:
#  - CentOS-fasttrack
```

**Comment by bertvv** [comment]
I added fenced code block markers so your code example is typeset correctly.

I'm closing this issue since it doesn't seem actionable, it that's all right for you. Don't hesitate to reopen it if you have suggestions for improvements.
